name: fitring
description: "ERBrains take-home assignment: a mobile app that syncs data from a wearable device and includes a small shopping flow"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.3.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1
  intl: ^0.20.1
  workmanager: ^0.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3


flutter:

  uses-material-design: true

